### ISSUE TITLE
Android testing failing on Windows with build tools 29.0

### ISSUE THREAD

**Issue by meteorcloudy** [android/testing-samples#306]
https://buildkite.com/bazel/android-testing/builds/634#81249842-64a0-4154-9b9f-7e718deed314
```
(00:03:15) ERROR: D:/b/xfb66erf/external/maven/BUILD:17:1: Couldn't build file external/maven/androidx_appcompat_appcompat_1_0_0_symbols/symbols.zip: Compiling Android resources for @maven//:androidx_appcompat_appcompat_1_0_0 failed (Exit 1)
Jan 30, 2020 12:03:15 AM java.util.stream.ForEachOps$ForEachOp$OfRef accept
SEVERE: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\drawable-xxhdpi-v4\abc_textfield_activated_mtrl_alpha.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
	compile\
	-v\
	--legacy\
	-o\
	D:\temp\android_resources_tmp4961863740124652290\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\drawable-xxhdpi-v4\abc_textfield_activated_mtrl_alpha.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\drawable-xxhdpi-v4\abc_textfield_activated_mtrl_alpha.9.png: note: compiling PNG.
 
Exception in thread "main" com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError
	at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileError.of(ResourceCompiler.java:110)
	at com.google.devtools.build.android.aapt2.ResourceCompiler$CompilingVisitor.getCompiledArtifacts(ResourceCompiler.java:422)
	at com.google.devtools.build.android.aapt2.ResourceCompiler.getCompiledArtifacts(ResourceCompiler.java:456)
	at com.google.devtools.build.android.UnvalidatedAndroidData.compile(UnvalidatedAndroidData.java:103)
	at com.google.devtools.build.android.CompileLibraryResourcesAction.main(CompileLibraryResourcesAction.java:140)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$10.call(ResourceProcessorBusyBox.java:120)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
	Suppressed: java.lang.RuntimeException: Error during Compiling bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\drawable-xxhdpi-v4\abc_textfield_activated_mtrl_alpha.9.png:
Command: external\androidsdk\build-tools\29.0.2\aapt2.exe\
	compile\
	-v\
	--legacy\
	-o\
	D:\temp\android_resources_tmp4961863740124652290\compiled\bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\drawable-xxhdpi-v4\abc_textfield_activated_mtrl_alpha.9.png
Output:
bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\resources\androidx_appcompat_appcompat_1_0_0\res\drawable-xxhdpi-v4\abc_textfield_activated_mtrl_alpha.9.png: note: compiling PNG.
 
		at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
		at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
		at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.compile(ResourceCompiler.java:226)
		at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:173)
		at com.google.devtools.build.android.aapt2.ResourceCompiler$CompileTask.call(ResourceCompiler.java:120)
		at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
		at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
		at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
```

/cc @jin

**Comment by meteorcloudy** [comment]
Similar to https://github.com/android/testing-samples/issues/303, this failure is probably due to some infra change, especially the build tool version change like https://github.com/bazelbuild/continuous-integration/commit/2f9b0b589622b21ab8a4bda4eb2060f685eebeca#diff-9882c48d58434ad0db15efe1564e83b3

@jin , should we revert to an older version of android build tools?
