### ISSUE TITLE
Unable to run the BasicSample Kotlin code

### ISSUE THREAD

**Issue by tudorsss** [android/testing-samples#333]
See the below screenshot for more details. I am using:

```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase, com.intellij.marketplace, com.thoughtworks.gauge
```

The same happens with:

```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase, com.intellij.marketplace, com.thoughtworks.gauge
```

This used to work a month ago.

<img width="1738" alt="Screenshot 2020-08-12 at 23 44 14" src="https://user-images.githubusercontent.com/12154831/90066737-cdbcf600-dcf6-11ea-8eeb-ae058fe3e2f4.png">

What am I doing wrong?

**Comment by hoisie** [comment]
Would this fix it:
https://stackoverflow.com/questions/48988778/cannot-inline-bytecode-built-with-jvm-target-1-8-into-bytecode-that-is-being-bui?

**Comment by tudorsss** [comment]
Hi @hoisie ,

Thanks for the reply. The accepted solution did fix the JVM target problem, but the code will still not run, see below:

```
java.lang.ClassNotFoundException: com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorKtTest
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:453)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.testing.espresso.BasicSample.ChangeTextBehaviorKtTest" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.example.android.testing.espresso.BasicSample.test-Hc2Bi9szuy-QHQoge5yrLg==/base.apk", zip file "/data/app/com.example.android.testing.espresso.BasicSample-GMrNiq8S9FhSM9rD22g5kQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.testing.espresso.BasicSample.test-Hc2Bi9szuy-QHQoge5yrLg==/lib/x86, /data/app/com.example.android.testing.espresso.BasicSample-GMrNiq8S9FhSM9rD22g5kQ==/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 8 more
```

<img width="1791" alt="Screenshot 2020-08-13 at 01 54 42" src="https://user-images.githubusercontent.com/12154831/90076322-18933980-dd08-11ea-8fec-eb18cf0a9323.png">

**Comment by hoisie** [comment]
I can repro the problem; will investigate

**Comment by hoisie** [comment]
Oddly it through the Gradle command line seems to work fine:
```
./gradlew cleanTest connectedAndroidTest
```

**Comment by hoisie** [comment]
@tudorsss this should be fixed now in the latest master
